name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: prefix-dev/setup-pixi@v0.4.3
        with:
          pixi-version: v0.12.0
          cache: true
      - name: Install external dependencies
        run: make install-external
      - name: Check formatting
        run: make check-format
      - name: Build
        run: make build-new
      - name: Test
        run: make test
