name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: taiki-e/install-action@just
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.23.0
          cache: false
      - name: Install external dependencies
        run: just install-external
        shell: pixi run bash {0}

      - name: Build
        run: just build-new ci
        shell: pixi run bash {0}

      - name: Test
        run: just test release
        shell: pixi run bash {0}

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: taiki-e/install-action@just
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.23.0
          cache: false
      - name: Install external dependencies
        run: just install-external
        shell: pixi run bash {0}

      - name: Build
        run: just build-new release
        shell: pixi run bash {0}

      - name: Check formatting
        run: just check-format
        shell: pixi run bash {0}

      - name: Lint
        run: just lint release
        shell: pixi run bash {0}
